# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ViewComponentsLib' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViewComponentsLib

  target 'ViewComponentsLibTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
